name: multiwiener_tf4
channels:
  - conda-forge
dependencies:
  - cudatoolkit=10.1
  - tensorflow-gpu=2.2.0
  - python=3.8.8
  - pip
  - nb_conda
  - numpy=1.18
  - matplotlib=3.4
  - scipy=1.4
  - opencv
  - imageio=2.9
  - ipykernel
  - ipython
  - scikit-image=0.18
